ignored = [
  "github.com/turbinelabs/nonstdlib*",
  "github.com/turbinelabs/test*",
  "github.com/golang/mock/*"
]

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  revision = "0a025b7e63adc15a622f29b0b2c4c3848243bbf6"
